[package]
name = "solitario"
version = "0.1.0"
authors = ["Andrés <nosoysaenz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
crossterm = "0.17"